# How many distinct terms are in the sequence
# generated by $a^{b}$ for $2 \leq a \leq 100$ and
# $2 \leq b \leq 100$?
# ----------------------------------------------------
# Analysis: brute force

print(len(set(a ** b for a in range(2, 101) for b in range(2, 101))))
